apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis-master
        image: redis:3.2.9
        ports:
        - name: redis-server
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: master
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - name: redis-slave
        image: ibmcom/guestbook-redis-slave:v2
        ports:
        - name: redis-server
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: slave
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-v1
  labels:
    app: guestbook
    version: "1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
        version: "1.0"
    spec:
      containers:
      - name: guestbook
        image: ibmcom/guestbook:v1
        ports:
        - name: http-server
          containerPort: 3000
        resources:
          requests:
             cpu: 100m
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lKQUtmbkVDZkVKaTNaTUEwR0NTcUdTSWIzRFFFQkN3VUFNQjR4SERBYUJnTlYKQkFNTUUyZDFaWE4wWW05dmF5NXRjM1JoYTNndWFXOHdIaGNOTVRrd056QTFNRGN5TURJNVdoY05Namt3TnpBeQpNRGN5TURJNVdqQWVNUnd3R2dZRFZRUUREQk5uZFdWemRHSnZiMnN1YlhOMFlXdDRMbWx2TUlJQklqQU5CZ2txCmhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBb25YcmNwZmQrQVFJYjMvbHhYODlpcnpIMktNYWdSYTAKalByK0JhcW9mUytmN25QQjY2MG9UWWVKMUlrNW9lazd4OWR2ZUFuUG91UkNqYnNnVGpKeDh0aXFNazg0cFQxbApFNFBwdHpFSERDMng3Y1YxOGxmNEl6dkRVUnMxKzIzcjJzT21VVnRrSkZybEc1Z3haZ2JWNzBUaDdIeG1RMDVDCmpqdllaZDVoNkY5U2s2N3pRSHA3V1VFQmtRQ1oxbXNXaUhIY2NIQzY5YjBCSHdLcnhMN2xEakY2QWpXZGhhdC8Kcnp0dmhieGhRbmJXWWM0blJsOUl6TFRwbTY4UlJyazdmem8va09aa1hVQ1FzZVhLQjZSZFdpNWRXMUZuemY2cgo1aG1ndmpKS2dsL1Rtc3pSTmdpNUxqZGdTcXJnVWRPMDV0cUV4dGlMcTlPRGFndk1oV0pOeXdJREFRQUJvMUF3ClRqQWRCZ05WSFE0RUZnUVV4SFdHNUs4S05HZEtkQkV4YjBnWVR2b2RHdUl3SHdZRFZSMGpCQmd3Rm9BVXhIV0cKNUs4S05HZEtkQkV4YjBnWVR2b2RHdUl3REFZRFZSMFRCQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBZitFWnFxNXdmL241LzJBVmg1T0Z1RGRnMldjNm5sd1lZcGZjM3hBckx2dFVWemVCUWJVUGY2ckJtNCtBCkNkMk01RDB2YldNd1FERGlVTElTc2tyMFY4clNBeEZYWEhLZEtPSTlvTVVFbXR5am1CWHo3Tk04RlMvSUFjd1YKTFBhWEpLWHpkaDNOcVNjdGRKaDcvdDNNb0pubkRyUHREbWUxTjE1cEUyeDRaRm5GQjZ5Mk1DQlBMVmpFNGp5QgpBTGE5NzM0dE1RS1JteEFWREJGRkxaZTBENllkbkUyM3ZyYnhtbXFudTJmejdGSXpaZllteDRkUGxRSUcrZW1FClM0YTVRUGFHTlhSU2NSSE5GNlpPQmN2Y2E1Nkt6aWFvOWVlVDZNOWxTRGpnaUZaZlRLeEdDR3FETk53WnRYRGMKSzVlYWVhS0J6aU1aOGQ4MU9pT3hsNCtVTUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBb25YcmNwZmQrQVFJYjMvbHhYODlpcnpIMktNYWdSYTBqUHIrQmFxb2ZTK2Y3blBCCjY2MG9UWWVKMUlrNW9lazd4OWR2ZUFuUG91UkNqYnNnVGpKeDh0aXFNazg0cFQxbEU0UHB0ekVIREMyeDdjVjEKOGxmNEl6dkRVUnMxKzIzcjJzT21VVnRrSkZybEc1Z3haZ2JWNzBUaDdIeG1RMDVDamp2WVpkNWg2RjlTazY3egpRSHA3V1VFQmtRQ1oxbXNXaUhIY2NIQzY5YjBCSHdLcnhMN2xEakY2QWpXZGhhdC9yenR2aGJ4aFFuYldZYzRuClJsOUl6TFRwbTY4UlJyazdmem8va09aa1hVQ1FzZVhLQjZSZFdpNWRXMUZuemY2cjVobWd2akpLZ2wvVG1zelIKTmdpNUxqZGdTcXJnVWRPMDV0cUV4dGlMcTlPRGFndk1oV0pOeXdJREFRQUJBb0lCQVFDYVlIdHYxU2cwT1lEYQpreXFBVmJ6aFRTcUtqZEx0dittcDNnZnMwcEp4QXdSeXpzVURjdlBOV0hKODZEay94aVhzYktlYjVaYk5MeUtmCkU2WkxLRnhuYThPdk11Q2RCSTQ3MFNvUnppRG9UYk82UWQwbWdMbG1vYStrTHJ0SlJOYk9kd1JnWXZ2eUgvMSsKRDAxQnFsVTRuTGdpeE1OWVNkR3MzdWx2UTdhOTIvTStobERIcEp4V0ZZRmoxOFdlZW55ek81VEZKT1gwNTFaaQpON04raUY2QkdnRG9rQ0NHSkQ2N1dIV0dSU3ltaWd6ZEVDY2piSCtTUVNLbUgxZUs4Q3MxK21XUGNwY1RTZmhpClJhcnFobFRCbGE3ajV0Q2hZKzdncjE2dTJsMXgvVlpnd3FHa1BTY3kveWNSK3NiNjhuOWJuRXMxeEZ5KzRvaloKVUtXcnJNMEJBb0dCQU0zY0lQK3Vib1FGaGhLUy82ZC9CLytXWkRqY1QvVCthcUJZM2ZYZldJSVV0MExpemFpRQpFL203R1dYa2ZsUlZkT29PUHVGMG1pQ2JLbnM0UzlRc2J6TDBqdmxibDNGY3pSQTVvTVMwa1JoZExCSzZoZ005Cm12VGVUbWV1aFZueWxjbXlVSE5mL2tNUThra2YwMHd0REpmZ0pxTlFVY2dhb2ZBN0R5OW1yczBoQW9HQkFNb0gKdllIY0RQZ2ZKNUw5QzVSSFRqR3N0bGZyOVpUWCtlc0Eyai81Z3Axb0duVzZFR1Ric0JHbmk0eGZjWEJvSHY4bwpQcXNzNWZzeHdHamQwRVBSaDhqQUx5WUJZWWtxMWpYSTlvemM0TnZBLzZpZ05rVUt4WjExaW9uNzlNY1RIN2luCnJoaTI4OFcvTUxGWkd0djFsSnVQOUFlSlRsYUJHVmJTZVFJNTUzRnJBb0dBQzNmZThyK0I4cUxvSkRMQ1FVK0gKWDRxK1RKaWhiN0dZdVJRYVVXOCszQWhSYVUxL1RZc0dIZHg1ZnI2cTl3SEh3SjVJaklEVmNVbVRwVWV1bWNSYgo4WWZFUzBuNTl0dkhwTWJCR1JSQ0hReGJ2ek5hOGVWRnM2eUt5NlhpVWU5OHZyN0xVcElmZFJjRm1HTklmeTduClM3SzJGRlVPS1VxcWlOcVJiditXYjJFQ2dZQjJNeGNkemVmTWx6V3BHdUZXYkcyRVJKOGVTNUFQK0ZoZ3RNdjgKRi9maUxoRWxCYW9ueUJ4NEI4VnVhRHpQWGl1Y2J5aFRMOTZTRzZhTjlCQ3dUUHViYVUxc2QreGZ1eTgrb29nVgpHL2wydUxFYk1EandKZ0ErUXBHK2J5bmordjFaSk1tSDdpb3JiTk9KUHkrbXQwU3R5d2drREtKSG5CcCtJSC9wCjNJVGJad0tCZ0JFdVBkdUdmLytTNDhaL1VoTXV6bTU1dGJMY0szUDk5SzJjYk1TQVhNNHRYZHNmNjhVbXdlengKdTZUK29vT2J4YjFKWHRMcnZlZGxJSmFJWXhmNXZsYmI3MlQxQWtyMGppSnRoWGZSSmdydjZRdDVDY1A4Sm50TApweU8rbU9lODlpM0QrQ2V6MG9UOUFiVzg0RXY3WE5ydlNiYjBtUFdGYTJtSjd1eFhNdThQCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: production-guestbook
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  ports:
  - port: 3000
    targetPort: http-server
  selector:
    app: guestbook
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook
spec:
  tls:
  - hosts:
    - guestbook.mstakx.io
    secretName: production-guestbook
  rules:
  - host: guestbook.mstakx.io
    http:
      paths:
      - path: /
        backend:
          serviceName: guestbook
          servicePort: 3000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: guestbook-v1
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: guestbook-v1
  targetCPUUtilizationPercentage: 50
